version: "3.9"
services:
  arangodb:
    image: arangodb:latest
    restart: always
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    # volumes:
      # - ${ARANGO_DATA_DIR}:/var/lib/arangodb3
    networks:
      - stix2arango
  postgresql:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${POSGRES_ROOT_PASSWORD}
      - POSTGRES_DB=stix2arango
    networks:
      - stix2arango
networks:
  stix2arango:
    driver: bridge